version: 2.1

orbs:
  node: circleci/node@4.7.0
  aws-cli: circleci/aws-cli@1.0.0

jobs:
  build_project:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Create deployment package
          command: |
            mkdir -p package
            cp -r node_modules package/
            cp -r src package/
            cp package.json package/
            cd package
            zip -r ../lambda_function.zip .
      - run:
          name: list directory
          command: ls
      - run:
          name: Check size of zip file
          command: ls -lh lambda_function.zip
      - persist_to_workspace:
          root: .
          paths:
            - lambda_function.zip

  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: list directory
          command: ls -R
      - run:
          name: Check size of zip file
          command: ls -lh lambda_function.zip
      - aws-cli/setup:
          aws-region: AWS_DEFAULT_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: Upload file to S3
          command: aws s3 cp lambda_function.zip s3://mindstride-lambda
      - run:
          name: Deploy to Lambda
          command: aws lambda update-function-code --function-name mindstride-express --s3-bucket mindstride-lambda --s3-key lambda_function.zip

workflows:
  deploy-to-lambda:
    jobs:
      - build_project
      - deploy_project:
          requires:
            - build_project
